### ISSUE TITLE
Implement a way to specify custom plugin logic and adding it to the XrmMockup execution pipeline.

### ISSUE THREAD

**Issue by mktange** [delegateas/XrmMockup#4]
Currently plugins can only be registered in the XrmMockup execution pipeline if they already exist as registered plugins in CRM, or if they have been registered as a Daxif Plugin.

Add a way to register additional/other plugins either in the constructor of XrmMockup or directly on an instance of XrmMockup.

**Comment by TomMalow** [comment]
I have added some new features in Mockup as part of commit https://github.com/delegateas/XrmMockup/commit/a05230232d2b92045fa2d176317749fa7c81f11c that allows users to register additional plugins.

This is handled by calling `RegisterAdditionalPlugins` which takes the plugin type and adds the plugin to the execution pipeline. The plugin is registered the same way that all other plugins are registered in XrmMockup. These plugins only exist until next call to `ResetEnvironment`.

I have also added a method for disabling standard plugins that were registered through the XrmMockup contructor. Allowing for testing a single plugin or a set of plugins instead of the all registered plugins.

Does this solution solves the issue?

**Comment by magesoe** [comment]
This has been implemented by @MattTrinder. One can now specify a MetaPlugin and MetaImage. 
```csharp
new MetaPlugin()
{
    AssemblyName = "DG.Some.Namespace.ContactIPluginDirectPreOp",
    MessageName = "Create",
    PrimaryEntity = "contact",
    Rank = 10,
    Stage = 20
}
```

These can be added to XrmMockup settings in the parameter `IPluginMetadata`. This will allow XrmMockup to search for those plugins. Simply make sure XrmMockup points to a class in your dll through the basePluginTypes and it works. For examples see the DirectPlugins folder in the SharedPluginsAndCodeactivities project
